import React, { useState, useRef, useEffect } from 'react';
import { useLocalStorageState } from '@pareeshy/use-local-storage-state';
import { PlaygroundDemoProps } from '../types';

interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'tool';
  content: string;
  timestamp: string;
  attachment?: string;
  toolCall?: {
    name: string;
    args: Record<string, any>;
    result?: string;
  };
}

const DETERMINISTIC_RESPONSES: Record<
  string,
  { text: string; tool?: { name: string; args: any; result: string } }
> = {
  default: {
    text: 'I am the local deterministic AI assistant powered by the @pareeshy ecosystem. I can inspect packages, simulate tool calling, stream tokens, and handle network edge cases offline with zero external API keys needed!'
  },
  weather: {
    text: 'I called the local weather tool to fetch real-time atmospheric conditions.',
    tool: {
      name: 'getWeatherConditions',
      args: { city: 'San Francisco', unit: 'celsius' },
      result: '☀️ 19°C, Clear skies, Humidity 58%, Wind 12 km/h'
    }
  },
  metrics: {
    text: 'Here is the performance report generated by the analyzePackageMetrics tool:',
    tool: {
      name: 'analyzePackageMetrics',
      args: { packages: 32, framework: 'React 18+' },
      result:
        'Total bundle size: <48KB gzipped. 100% Tree-shakeable, 0 external runtime dependencies.'
    }
  }
};

export function AiAssistantDemo({ log, resetKey }: PlaygroundDemoProps) {
  const [messages, setMessages] = useLocalStorageState<ChatMessage[]>(
    'playground_ai_chat_history',
    [
      {
        id: 'welcome-1',
        role: 'assistant',
        content:
          'Hello! I am your offline AI assistant. Ask me to test streaming, cancellation, attachments, or tool calling.',
        timestamp: new Date().toLocaleTimeString()
      }
    ]
  );

  const [input, setInput] = useState('');
  const [isStreaming, setIsStreaming] = useState(false);
  const [streamDelayMs, setStreamDelayMs] = useState(30);
  const [initialLatencyMs, setInitialLatencyMs] = useState(500);
  const [simulateError, setSimulateError] = useState(false);
  const [forceToolCall, setForceToolCall] = useState(false);
  const [attachedFile, setAttachedFile] = useState<string | null>(null);
  const [hasError, setHasError] = useState(false);

  const abortControllerRef = useRef<AbortController | null>(null);

  useEffect(() => {
    log(
      'info',
      'Initialized AI Assistant Demo (Deterministic Local Mock AI with Streaming & Tool Calling)'
    );
  }, [resetKey]);

  const cancelStreaming = () => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
      abortControllerRef.current = null;
      setIsStreaming(false);
      log('warning', 'AI stream aborted by user via cancellation signal');
    }
  };

  const handleSend = async (customPrompt?: string) => {
    const promptText = (customPrompt ?? input).trim();
    if (!promptText || isStreaming) return;

    const userMsg: ChatMessage = {
      id: 'msg_' + Date.now(),
      role: 'user',
      content: promptText,
      timestamp: new Date().toLocaleTimeString(),
      attachment: attachedFile ?? undefined
    };

    setMessages((prev) => [...prev, userMsg]);
    setInput('');
    setAttachedFile(null);
    setHasError(false);
    setIsStreaming(true);

    log('info', `User Prompt: "${promptText}"`, { attachedFile });

    const abortController = new AbortController();
    abortControllerRef.current = abortController;

    try {
      // 1. Initial simulated response latency
      await new Promise((resolve, reject) => {
        const timeout = setTimeout(resolve, initialLatencyMs);
        abortController.signal.addEventListener('abort', () => {
          clearTimeout(timeout);
          reject(new DOMException('Aborted', 'AbortError'));
        });
      });

      // 2. Simulated Error Check
      if (simulateError) {
        throw new Error('503 Service Unavailable: AI Worker connection timeout (Simulated error)');
      }

      // 3. Determine response template and potential tool calls
      const isWeather = promptText.toLowerCase().includes('weather');
      const isMetrics =
        promptText.toLowerCase().includes('metrics') ||
        promptText.toLowerCase().includes('package');
      const choice =
        forceToolCall || isWeather
          ? isWeather
            ? DETERMINISTIC_RESPONSES.weather!
            : DETERMINISTIC_RESPONSES.metrics!
          : isMetrics
            ? DETERMINISTIC_RESPONSES.metrics!
            : DETERMINISTIC_RESPONSES.default!;

      // Execute simulated tool call if required
      if (choice.tool) {
        log('info', `AI invoking tool: [${choice.tool.name}]`, choice.tool.args);
        await new Promise((r) => setTimeout(r, 400));
        log('success', `Tool [${choice.tool.name}] returned result:`, choice.tool.result);
      }

      // 4. Create empty assistant message container
      const assistantId = 'ai_' + Date.now();
      const assistantMsg: ChatMessage = {
        id: assistantId,
        role: 'assistant',
        content: '',
        timestamp: new Date().toLocaleTimeString(),
        toolCall: choice.tool
      };

      setMessages((prev) => [...prev, assistantMsg]);

      // 5. Stream response tokens
      const words = choice.text.split(' ');
      let accumulated = '';

      for (let i = 0; i < words.length; i++) {
        if (abortController.signal.aborted) {
          throw new DOMException('Aborted', 'AbortError');
        }

        accumulated += (i > 0 ? ' ' : '') + words[i];

        setMessages((prev) =>
          prev.map((msg) => (msg.id === assistantId ? { ...msg, content: accumulated } : msg))
        );

        await new Promise((resolve, reject) => {
          const t = setTimeout(resolve, streamDelayMs);
          abortController.signal.addEventListener('abort', () => {
            clearTimeout(t);
            reject(new DOMException('Aborted', 'AbortError'));
          });
        });
      }

      log('success', `AI stream finished (${words.length} tokens emitted)`);
    } catch (err: any) {
      if (err.name === 'AbortError') {
        log('warning', 'Generation was cancelled successfully.');
      } else {
        setHasError(true);
        log('error', `AI Generation Error: ${err.message}`);
        setMessages((prev) => [
          ...prev,
          {
            id: 'err_' + Date.now(),
            role: 'assistant',
            content: `⚠️ Error: ${err.message}`,
            timestamp: new Date().toLocaleTimeString()
          }
        ]);
      }
    } finally {
      setIsStreaming(false);
      abortControllerRef.current = null;
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      {/* Simulation Controls Panel */}
      <div
        style={{
          padding: 14,
          borderRadius: 'var(--radius-md)',
          backgroundColor: 'var(--stripe-bg-subtle)',
          border: '1px solid var(--stripe-border)',
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
          gap: 12
        }}
      >
        <div>
          <label
            style={{
              fontSize: '0.78rem',
              fontWeight: 600,
              color: 'var(--text-head)',
              display: 'block',
              marginBottom: 4
            }}
          >
            Response Latency: {initialLatencyMs}ms
          </label>
          <input
            type="range"
            min={100}
            max={2000}
            step={100}
            value={initialLatencyMs}
            onChange={(e) => setInitialLatencyMs(Number(e.target.value))}
            style={{ width: '100%' }}
          />
        </div>

        <div>
          <label
            style={{
              fontSize: '0.78rem',
              fontWeight: 600,
              color: 'var(--text-head)',
              display: 'block',
              marginBottom: 4
            }}
          >
            Stream Speed: {streamDelayMs}ms / token
          </label>
          <input
            type="range"
            min={10}
            max={150}
            step={10}
            value={streamDelayMs}
            onChange={(e) => setStreamDelayMs(Number(e.target.value))}
            style={{ width: '100%' }}
          />
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 6, paddingTop: 4 }}>
          <label
            style={{
              fontSize: '0.78rem',
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              cursor: 'pointer'
            }}
          >
            <input
              type="checkbox"
              checked={simulateError}
              onChange={(e) => setSimulateError(e.target.checked)}
            />
            Simulate Server Error (503)
          </label>

          <label
            style={{
              fontSize: '0.78rem',
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              cursor: 'pointer'
            }}
          >
            <input
              type="checkbox"
              checked={forceToolCall}
              onChange={(e) => setForceToolCall(e.target.checked)}
            />
            Force Simulated Tool Call
          </label>
        </div>
      </div>

      {/* Chat Messages Log */}
      <div
        style={{
          border: '1px solid var(--stripe-border)',
          borderRadius: 'var(--radius-md)',
          backgroundColor: 'var(--stripe-bg-surface)',
          padding: 16,
          height: 260,
          overflowY: 'auto',
          display: 'flex',
          flexDirection: 'column',
          gap: 12
        }}
      >
        {messages.map((msg) => {
          const isUser = msg.role === 'user';
          return (
            <div
              key={msg.id}
              style={{
                alignSelf: isUser ? 'flex-end' : 'flex-start',
                maxWidth: '85%',
                backgroundColor: isUser ? 'var(--primary)' : 'var(--stripe-bg-subtle)',
                color: isUser ? '#fff' : 'var(--text-head)',
                padding: '10px 14px',
                borderRadius: 'var(--radius-md)',
                fontSize: '0.85rem',
                lineHeight: 1.5,
                boxShadow: 'var(--shadow-sm)',
                border: isUser ? 'none' : '1px solid var(--stripe-border)'
              }}
            >
              <div
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  gap: 12,
                  marginBottom: 4,
                  opacity: 0.7,
                  fontSize: '0.7rem'
                }}
              >
                <strong>{isUser ? 'You' : '🤖 Assistant'}</strong>
                <span>{msg.timestamp}</span>
              </div>

              {msg.attachment && (
                <div
                  style={{
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: 6,
                    padding: '2px 8px',
                    borderRadius: 4,
                    backgroundColor: 'rgba(0, 0, 0, 0.15)',
                    fontSize: '0.75rem',
                    marginBottom: 6
                  }}
                >
                  📎 {msg.attachment}
                </div>
              )}

              {/* Tool Call Box */}
              {msg.toolCall && (
                <div
                  style={{
                    backgroundColor: 'var(--code-bg)',
                    borderRadius: 6,
                    border: '1px solid var(--code-border)',
                    padding: 8,
                    marginBottom: 8,
                    fontFamily: 'var(--font-mono)',
                    fontSize: '0.75rem'
                  }}
                >
                  <div style={{ color: 'var(--code-fn)', fontWeight: 700 }}>
                    ⚡ Tool Executed: {msg.toolCall.name}()
                  </div>
                  <div style={{ color: 'var(--code-comment)', marginTop: 2 }}>
                    Args: {JSON.stringify(msg.toolCall.args)}
                  </div>
                  {msg.toolCall.result && (
                    <div style={{ color: 'var(--code-str)', marginTop: 4 }}>
                      Result: {msg.toolCall.result}
                    </div>
                  )}
                </div>
              )}

              <div>{msg.content}</div>
            </div>
          );
        })}

        {isStreaming && (
          <div
            style={{
              alignSelf: 'flex-start',
              fontSize: '0.78rem',
              color: 'var(--primary)',
              fontWeight: 600
            }}
          >
            ⏳ AI is generating tokens in real-time...
          </div>
        )}
      </div>

      {/* Input & Action Bar */}
      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter') handleSend();
          }}
          placeholder="Ask a question or test tool calling (e.g. 'check weather' or 'analyze metrics')..."
          disabled={isStreaming}
          style={{
            flex: '1 1 280px',
            padding: '10px 14px',
            borderRadius: 'var(--radius-sm)',
            border: '1px solid var(--stripe-border)',
            backgroundColor: 'var(--stripe-bg)',
            color: 'var(--text-head)',
            fontSize: '0.9rem'
          }}
        />

        <button
          onClick={() => {
            setAttachedFile('schema_spec.json (14 KB)');
            log('info', 'Attached mock file: schema_spec.json');
          }}
          disabled={isStreaming || Boolean(attachedFile)}
          style={{
            padding: '8px 12px',
            borderRadius: 'var(--radius-sm)',
            border: '1px solid var(--stripe-border)',
            backgroundColor: attachedFile ? 'var(--primary-light)' : 'var(--stripe-bg-subtle)',
            color: attachedFile ? 'var(--primary)' : 'var(--text-head)',
            fontSize: '0.82rem',
            cursor: isStreaming ? 'not-allowed' : 'pointer'
          }}
        >
          {attachedFile ? '📎 Attached' : '📎 Add Attachment'}
        </button>

        {isStreaming ? (
          <button
            onClick={cancelStreaming}
            style={{
              padding: '8px 16px',
              borderRadius: 'var(--radius-sm)',
              backgroundColor: '#ef4444',
              color: '#fff',
              border: 'none',
              fontWeight: 700,
              cursor: 'pointer'
            }}
          >
            🛑 Stop / Cancel
          </button>
        ) : (
          <button
            onClick={() => handleSend()}
            disabled={!input.trim()}
            style={{
              padding: '8px 20px',
              borderRadius: 'var(--radius-sm)',
              backgroundColor: 'var(--primary)',
              color: '#fff',
              border: 'none',
              fontWeight: 700,
              cursor: !input.trim() ? 'not-allowed' : 'pointer',
              opacity: !input.trim() ? 0.5 : 1
            }}
          >
            Send Prompt
          </button>
        )}

        {hasError && (
          <button
            onClick={() => {
              setSimulateError(false);
              handleSend('Retry previous prompt');
              log('info', 'Retrying previous request with errors disabled...');
            }}
            style={{
              padding: '8px 14px',
              borderRadius: 'var(--radius-sm)',
              backgroundColor: 'var(--warning-bg)',
              color: 'var(--warning)',
              border: '1px solid var(--warning)',
              fontWeight: 700,
              cursor: 'pointer'
            }}
          >
            🔄 Retry
          </button>
        )}

        <button
          onClick={() => {
            setMessages([
              {
                id: 'welcome-1',
                role: 'assistant',
                content: 'Chat history cleared. State reset.',
                timestamp: new Date().toLocaleTimeString()
              }
            ]);
            log('warning', 'Cleared chat history from persisted storage');
          }}
          style={{
            padding: '8px 12px',
            borderRadius: 'var(--radius-sm)',
            border: '1px solid var(--stripe-border)',
            backgroundColor: 'transparent',
            color: 'var(--text-muted)',
            fontSize: '0.8rem',
            cursor: 'pointer'
          }}
        >
          Clear Chat
        </button>
      </div>
    </div>
  );
}
